### ISSUE TITLE
Error while running `scan-config` script

### ISSUE THREAD

**Issue by nhatphongdo** [woowabros/nestjs-library-config#95]
While implementing our system, we face this issue when `scan-config` script runs to generate the README file.
```
❯ nx run app:scan-config --verbose

> nx run app:scan-config

running ConfigScanner { sourceRoots: 'apps/app/src' }
 serializing DatabaseConfigService
 serializing AppConfigService
 serializing RedisCacheConfig
 >  NX   ElementType is not defined
ReferenceError: ElementType is not defined
    at eval (eval at convertValue (/Users/phong.do/Projects/monorepo/node_modules/@nestjs-library/config/dist/lib/config-scanner.js:301:16), <anonymous>:3:1)
    at ConfigScanner.convertValue (/Users/phong.do/Projects/monorepo/node_modules/@nestjs-library/config/dist/lib/config-scanner.js:301:47)
    at visit (/Users/phong.do/Projects/monorepo/node_modules/@nestjs-library/config/dist/lib/config-scanner.js:135:48)
    at visitNodes (/Users/phong.do/Projects/monorepo/node_modules/@nestjs-library/config/node_modules/typescript/lib/typescript.js:27591:24)
    at forEachChildInSourceFile (/Users/phong.do/Projects/monorepo/node_modules/@nestjs-library/config/node_modules/typescript/lib/typescript.js:28211:18)
    at Object.forEachChild (/Users/phong.do/Projects/monorepo/node_modules/@nestjs-library/config/node_modules/typescript/lib/typescript.js:27676:37)
    at ConfigScanner.<anonymous> (/Users/phong.do/Projects/monorepo/node_modules/@nestjs-library/config/dist/lib/config-scanner.js:158:38)
    at Generator.next (<anonymous>)
    at /Users/phong.do/Projects/monorepo/node_modules/@nestjs-library/config/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target scan-config for project app failed

   Failed tasks:
   
   - app:scan-config
```

**Comment by jiho-kr** [comment]
I`m looking at this issue.

**Comment by jiho-kr** [comment]
I haven't been able to `reproduce it with spec`, but I can see why.

This will be resolved with https://github.com/woowabros/nestjs-library-config/pull/96
